title:             Bosque de Corazones
email:             equipo@somosazucar.org
description:       Salvar la Amazon√≠a
author:            Equipo Bosque de Corazones
baseurl:           "/"
url:               "http://bosquedecorazones.club"

# Social Profiles
twitter_username:  arbioperu
github_username:   arbio
facebook_username: arbioperu

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
